### ISSUE TITLE
Allow code snippets in multiple programming language

### ISSUE THREAD

**Issue by mvysny** [gjtorikian/commonmarker#124]
Hello, building on https://github.com/github/markup/issues/435 , would it be possible to add support for having example code snippets in multiple programming languages, similar to https://yassir.dev/markdown-fenced-code-tabs/ please?

Thank you kindly :)

**Comment by gjtorikian** [comment]
Hi there, thank you for opening an issue. Since this would be an addition to the formal Commonmark spec, I suggest opening it over where the development of that spec occurs: https://github.com/github/cmark-gfm

The intent of this repository is to just prove a single Ruby wrapper for the existing C code. It does not add any features that do not already exist in `github/cmark-gfm`.

Alternative, you are free to create your own custom renderer as a plugin/add-on: https://github.com/gjtorikian/commonmarker#creating-a-custom-renderer. For example, you can see how [commonmarker-rouge](https://github.com/sandfoxme/commonmarker-rouge) added syntax highlighting to code blocks on top of this gem.

**Comment by mvysny** [comment]
Thank you for letting me know and for the pointers, I created the feature request as you suggested. Thanks again :+1:
