### ISSUE TITLE
Smart punctuation and hardbreaks don't mix in render_doc

### ISSUE THREAD

**Issue by GimliLongBow** [gjtorikian/commonmarker#17]
Hello!

I'm working on a project and we liked the idea of mixing smart punctuation and hardbreaks using a custom renderer. When I did so, however, commonmarker failed to render the hardbreaks. I've set up a failing test here:

https://github.com/GimliLongBow/commonmarker/commit/8e5a08fde1dbdaa656346f1eb49aeda2cd5a372f

Looks like the straight `render_html` call works fine and `render_doc` doesn't. I'd love to try to figure this out, but I'm not sure if the problem is in the Ruby wrapper or the C library. Can you point me in the right direction? 

Thanks!

**Comment by gjtorikian** [comment]
Hi there! If you want to take a look at providing a fix, the problem is almost certainly on the Ruby side, [around this line](https://github.com/gjtorikian/commonmarker/blob/5b8571932b3c2db94563ead16a70c56b6b276a0d/lib/commonmarker/config.rb#L23), where options are combined before being handed off to C. Otherwise I can take a look in a few days or so.

**Comment by GimliLongBow** [comment]
Hmm. Poking around, it seems that the correct value (10) is being generated by the config line. After some more poking, `render_html` and `render_doc` both generate the wrong output; evidently one failing test in the file makes it ignore running the other test (that might be me). I'll keep doing some digging.

**Comment by GimliLongBow** [comment]
That's excellent! Thanks for digging in and fixing this!
