### ISSUE TITLE
Ruby 3.1 required?

### ISSUE THREAD

**Issue by digitalmoksha** [gjtorikian/commonmarker#222]
I was wondering, is it necessary to require 3.1, or could it be relaxed to 3.0? We're making the move to 3.0, not sure when we'll upgrade to 3.1

**Comment by gjtorikian** [comment]
Nope, sorry. 3.1 is firm.

The Windows RubyInstaller fixed a critical bug (imho) in 3.1: https://rubyinstaller.org/2021/12/31/rubyinstaller-3.1.0-1-released.html

> In particular the ruby and gem platform is now x64-mingw-ucrt instead of x64-mingw32 and the MSYS2 package prefix is now mingw-w64-ucrt-x86_64-. 

To make my life easier and not have to keep in mind how platform strings change, I want this to be availabile for 3.1 and above. 3.1 also has a better JIT and async improvements. 

In my opinion, just make the jump to 3.2, rather than stopping at 3.0.
