### ISSUE TITLE
Change in default `extension.header_ids` value

### ISSUE THREAD

**Issue by GabeIsman** [gjtorikian/commonmarker#326]
I just wanted to make sure you're aware that the recent 2.0 (and 2.0.1) releases have changed the default value of `extension.header_ids`. I'm now getting Github-style header ID anchors when I  wasn't before. Setting
```ruby
extension: {
  ...,
  header_ids: nil
}
```
restores the old behavior. 

If this change was intentional, maybe it could be noted in the release notes? Thanks!

**Comment by gjtorikian** [comment]
Hiya! Thanks for the report. Yes, this was intentional. I've updated the CHANGELOG to reflect this.

The short answer is that this should have _always_ been like this, but wasn't. I think your sentiment matches #318, in that this rendering isn't part of any Commonmark spec. But while the gem can be made spec complete, it's not spec complete by default. I think automatically anchor IDs for headers is A Good Thing; but as you've noted, it takes a little more configuration to remove now.

**Comment by GabeIsman** [comment]
Got it! Makes sense. I think the surprising part for me was related to the options merging changes. I gather that in previous versions the options I was passing were shadowing the defaults completely, so `header_ids` was "default" `nil` but unintentionally!
