### ISSUE TITLE
Github/CommonMarker is parsing images/markup inconsistently.

### ISSUE THREAD

**Issue by leegao** [gjtorikian/commonmarker#41]
Hey guys, I love what you are doing here. A few days ago, I noticed a weird inconsistency. I found a simple repro at https://gist.github.com/leegao/8f1a03490f627067270e0dc3d436f746

Essentially, I have a `<p>` block wrapping an image (in `bad.md`), and if I don't add a blank line after that image block, the following markup gets either ignored (for example, the next inline code span) or similarly wrapped in a paragraph (see the formula).

However, if I add a blank line immediately after the `<p>` image block (as in `okay.md`), then the problem no longer manifests.

I haven't had a chance to dig through the stream of commits that may have caused this, and I'm not sure whether this is high-priority enough from your end, or even if this is a bug owned by commonmarker versus cmark. Either case, I thought it would be a good idea to flag it for you guys in case anything is actionable.

**Comment by kivikakk** [comment]
:wave: Hey there! Thanks for writing in!

This is in fact not even a bug, but expected behaviour per the specification. You can check this by [pasting it into the CommonMark demo](http://spec.commonmark.org/dingus/?text=In%20addition%2C%20while%20other%20Github%20TeX%20renderers%20tend%20to%20give%20a%20jumpy%20look%20to%20the%20compiled%20text%2C%20%0A%3Cp%20align%3D%22center%22%3E%0A%3Cimg%20src%3D%22http%3A%2F%2Fi.imgur.com%2FXSV1rPw.png%3F1%22%20width%3D500%2F%3E%0A%3C%2Fp%3E%0A%60readme2tex%60%20ensures%20that%20inline%20mathematical%20expressions%0Aare%20properly%20aligned%20with%20the%20rest%20of%20the%20text%20to%20give%20a%20more%20natural%20look%20to%20the%20document.%20For%20example%2C%0Athis%20equation%20%3Cimg%20src%3D%22https%3A%2F%2Frawgit.com%2Fleegao%2Freadme2tex%2Fsvgs%2Fsvgs%2F24a7d013bfb0af0838f476055fc6e1ef.svg%3Finvert_in_darkmode%22%20align%3Dmiddle%20width%3D13.784595pt%20height%3D31.42491pt%2F%3E%20is%20preprocessed%20so%20that%20it%20lines%20up%20at%20the%20correct%20baseline%20for%20the%20text.%0AThis%20is%20the%20one%20salient%20feature%20of%20this%20package%20compared%20to%20the%20others%20out%20there.) and seeing the output is the same.

The details of this are covered in the [HTML block section of the specification](http://spec.commonmark.org/0.27/#html-blocks). In short, the CommonMark parser enters "HTML block mode" when it hits a `<p>` tag, and per Start Condition 6, it remains in that mode — not parsing any of the content as Markdown, but passing it straight through — until the next empty line. So, an empty line is required to return the parser to regular Markdown mode.

Hope this helps!

**Comment by leegao** [comment]
Ahh gotcha, that totally makes sense. Thanks for looking into this :)

**Comment by kivikakk** [comment]
No probs! Feel free to ping us again here or on the [`github/cmark`](https://github.com/github/cmark) repo for questions about the Markdown implementation itself; also, [CommonMark Discussion](https://talk.commonmark.org/) is where decisions regarding the specification itself get talked through. :)
