### ISSUE TITLE
Request : Image Size Issues

### ISSUE THREAD

**Issue by maxswjeon** [gjtorikian/commonmarker#84]
Since Github is using commonmarker on Markdown files, (.markdown, .md, .etc...) I came here to suggest new features.
There is no way to resize images if they are bigger than wrapper width. There were some ways to resize them by pipe or additional curly braces (https://gist.github.com/uupaa/f77d2bcf4dc7a294d109)
Is there any further plans for image resizing?

**Comment by gjtorikian** [comment]
Hi -- since this would be an addition to the formal Commonmark spec, I suggest opening it over where the development of that spec occurs: https://github.com/github/cmark-gfm

The intent of this repository is to just prove a single Ruby wrapper for the existing C code. It does not add any features that do not already exist in `github/cmark-gfm`.

Good luck with your request!
