### ISSUE TITLE
Code block vanishes in latest with commonmarker-rouge

### ISSUE THREAD

**Issue by scivola** [gjtorikian/commonmarker#85]
Reproduction:

```rb
# Gemfile

source "https://rubygems.org"

gem 'commonmarker', '0.18.1'
gem 'commonmarker-rouge'
```

~~~rb
require "bundler"
Bundler.require

source = <<'EOT'
```rb
x
```
EOT

puts CommonMarker::Rouge.render_html(source)
~~~

Result:

```
<!-- raw HTML omitted -->
```

Why???

But if we change commonmarker version to 0.17.13, the result is okay:

```
<div class="highlighter-rouge language-rb"><span class="n">x</span>
</div>
```

Also, if we omit the language specifier, namely change 

~~~
```rb
~~~

to

~~~
```
~~~

the result is okay:

```
<pre><code>x
</code></pre>
```

**Comment by gjtorikian** [comment]
Sorry about that! In https://github.com/gjtorikian/commonmarker/pull/81, we began to disallow "custom" HTML by default. Previously, `DEFAULT` allowed anything to come through, but for security reasons, we've restricted the HTML to _just_ the Commonmarker subset. Since syntax highlighting includes `div`s, `span`s, and other elements, you'll need to render the document as "unsafe."

With the newest release of this gem, you can work around the problem with

``` ruby
puts CommonMarker::Rouge.render_html(source, [:UNSAFE])
```

However, I would highly recommend @sandfoxme to swap the `commonmarker-rouge` library from using `DEFAULT` to `UNSAFE`, so that users do not need to do this.

**Comment by scivola** [comment]
Thank you for the update.

But I can not obtain the expected result.

I changed

```rb
gem 'commonmarker', '0.18.1'
```

to 

```rb
gem 'commonmarker', '0.18.2'
```

in Gemfile, and changed

```rb
puts CommonMarker::Rouge.render_html(source)
```

to

```rb
puts CommonMarker::Rouge.render_html(source, [:UNSAFE])
```

and do:

```
bundle update
```

The result of the script is still:

```
<!-- raw HTML omitted -->
```

**Comment by gjtorikian** [comment]
Ah, yeah, then this is definitely something to be fixed in the upstream library, sorry.

commonmarker-rouge defines `render_html` as:

``` ruby
    def render_html(text, cmark_options = :DEFAULT, **cmr_options)
      render_doc(text, cmark_options, **cmr_options).to_html
    end
```

But [`to_html`](https://github.com/gjtorikian/commonmarker/blob/1469be1918214f18ae070bcc6144aabe58a7f5db/lib/commonmarker/node.rb#L26) takes options, and the default is `DEFAULT`. The commonmarker-rouge library needs to pass in `UNSAFE` here.
