### ISSUE TITLE
Please add an option for accessible footnotes

### ISSUE THREAD

**Issue by borisschapira** [gjtorikian/commonmarker#89]
In the `html_renderer.rb`, please add an `aria-label` attribute to the footnote "↩" backlink with a default "Back to content" value.
In a second time, allow this value to be modified by a configuration so that developers at the end of the chain could configure a localized value depending on the content locale.

**Comment by gjtorikian** [comment]
Hi there, thank you for opening an issue. Since this would be an addition to the formal Commonmark spec, I suggest opening it over where the development of that spec occurs: https://github.com/github/cmark-gfm

The intent of this repository is to just prove a single Ruby wrapper for the existing C code. It does not add any features that do not already exist in `github/cmark-gfm`.

Alternative, you are free to create your own custom renderer as a plugin/add-on: https://github.com/gjtorikian/commonmarker#creating-a-custom-renderer. For example, you can see how [commonmarker-rouge](https://github.com/sandfoxme/commonmarker-rouge) added syntac highlighting to code blocks on top of this gem.

**Comment by gjtorikian** [comment]
Ah, my apologies, I did a quick re-read and the autoreply there isn't entirely accurate. The `aria-label` generation issue would still need to be opened by https://github.com/github/cmark-gfm (but this isn't technically a new addition to the spec, I don't think?).

**Comment by borisschapira** [comment]
Sorry to have bothered you. I saw that the code came from [a renderer defined in this project] (https://github.com/gjtorikian/commonmarker/blob/master/lib/commonmarker/renderer/html_renderer.rb#L239), so I opened an issue here. The Custom Renderer may be a solution, I'll propose it to [jekyll-commonmark](https://github.com/jekyll/jekyll-commonmark). As I don't see any renderer in cmark-gfm, I wonder how it could be handled there.
